version: '3'
services:
  rabbit:
    image: rabbitmq:3.8.3
    ports:
      - '5672:5672'
    networks:
      - network
  send:
    build: ./send
    environment:
      - RABBIT_SERVER=rabbit
      - RABBIT_QUEUE=clicks
    depends_on:
      - rabbit
    networks:
      - network
  receive:
    build: ./receive
    environment:
      - RABBIT_SERVER=rabbit
      - RABBIT_QUEUE=clicks
    volumes:
      - volume:/tmp
    depends_on:
      - send
    networks:
      - network
  display:
    build: ./display
    ports:
      - '5000:5000'
    volumes:
      - volume:/tmp
    depends_on:
      - receive
networks:
  network: {}
volumes:
  volume:
